name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover      
    #- name: setup code coverage
    #  run: dotnet tool install --global Codecov.Tool
    #- name: generate code coverage report   
    #  run: codecov -f ${{ env.GITHUB_WORKSPACE }}/coverage.rpt
    - name: Codecov
      # You may pin to the exact commit or the version.
      # uses: codecov/codecov-action@a1ed4b322b4b38cb846afb5a0ebfa17086917d27
      uses: codecov/codecov-action@v1.5.0
      with:
        token: 42a282f9-754f-4617-a349-9da26505f930
        fail_ci_if_error: true

      
